[[bridges]]
name = "mautrix-instagram"
maintainer = "Tulir"
summary = """
A Matrix-Instagram DM puppeting bridge. Written in Python using
[mauigpapi](https://github.com/mautrix/instagram/tree/master/mauigpapi) and
[mautrix-python](https://matrix.org/docs/projects/sdk/mautrix-python.html).
"""
maturity = "Beta"
language = "Python"
license = "AGPL-3.0-or-later"
docs = "https://docs.mau.fi/bridges/go/setup.html?bridge=instagram"
repo = "https://github.com/mautrix/instagram"
room = "#instagram:maunium.net"
featured = true
privilege.platform = "User" # Free text
privilege.matrix = "Homeserver Admin" # Any of Homeserver Admin, Room Admin, None
[bridges.supports]
dm = true
message_media = true
redactions = true
reactions = true
presence = false
typing_notifications = true
read_receipts = true

[[bridges]]
name = "mautrix-meta"
maintainer = "Tulir"
summary = """
A Matrix-Facebook Messenger and Instagram DM puppeting bridge.
"""
maturity = "Alpha"
language = "Go"
license = "AGPL-3.0-or-later"
docs = "https://docs.mau.fi/bridges/go/setup.html?bridge=meta"
repo = "https://github.com/mautrix/meta"
room = "#meta:maunium.net"
featured = true
privilege.platform = "User" # Free text
privilege.matrix = "Homeserver Admin" # Any of Homeserver Admin, Room Admin, None
[bridges.supports]
dm = true
message_media = true
redactions = true
reactions = true
presence = false
typing_notifications = false
read_receipts = false

[[bridges]]
name = "matrix-appservice-instagram-media"
maintainer = "Travis Ralston"
summary = """
This is a bridge to post Instagram media into matrix rooms, with authorization. This bridge does not handle chat and cannot post to Instagram on your behalf, but it is useful for organizations looking to have their Instagram accounts also post to matrix.
"""
maturity = "Obsolete"
language = "Javascript"
license = "GPL-3.0-only"
repo = "https://github.com/turt2live/matrix-appservice-instagram"
room = "#instagram:t2bot.io"
featured = false
privilege.platform = "User" # Free text
privilege.matrix = "Homeserver Admin" # Any of Homeserver Admin, Room Admin, None
[bridges.supports]
matrix_to_instagram_messaging = false
messaging_without_instagram_account = false
