name: Update public instances
on:
  # Delete push: and replace with schedule before merging to main
  push:
    branches:
      - instance-picker

jobs:
  run:
    # Delete with: ref: instance-picker before merging to main
    name: Update public instances
    runs-on: ubuntu-latest
    steps:
      - name: Checkout matrix.org source
        uses: actions/checkout@v4
        with:
          path: 'morg'
          ref: instance-picker

      - name: Checkout the public instance updater
        uses: actions/checkout@v4
        with:
          repository: 'thibaultamartin/public-instances-updater'
          path: 'piu'

      - name: Update public instance data on the runner
        run: |
          cp morg/content/public-instances/instances.toml piu/instances.toml
          cd piu && yarn && yarn run update && cd ..
          cp piu/instances.toml morg/content/public-instances/instances.toml

      # Delete this step before merging to main
      - name: Commit and push data (within PR)
        run: |
          git config --global user.name "GitHub CI"
          git config --global user.email "noreply@matrix.org"
          git switch instance-picker
          git add public-instances/instances.toml
          git commit -m "Update instances.toml"
          git push
        working-directory: morg

      # Delete the if before merging to main
      - name: Commit and push data (scheduled)
        if: github.event_name == 'schedule'
        run: |
          git config --global user.name "GitHub CI"
          git config --global user.email "noreply@matrix.org"
          git add public-instances/instances.toml
          git commit -m "Update instances.toml"
          git push
        working-directory: morg
